
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.FileReader;
import java.util.Scanner;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Amna
 */
public class LoginPage extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public LoginPage() {
        initComponents();
        setLocationRelativeTo(null); // Center the window on the screen
         ActionListener loginAction = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                loginbtn.doClick();
            }
        };
        username.addActionListener(loginAction);
        passtxt.addActionListener(loginAction);

    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        loginbtn = new javax.swing.JButton();
        signupbtn = new javax.swing.JButton();
        username = new javax.swing.JTextField();
        passtxt = new javax.swing.JPasswordField();
        showbox = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loginbtn.setBackground(new java.awt.Color(153, 0, 51));
        loginbtn.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        loginbtn.setForeground(new java.awt.Color(255, 255, 255));
        loginbtn.setText("LOGIN");
        loginbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginbtnMouseClicked(evt);
            }
        });
        loginbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginbtnActionPerformed(evt);
            }
        });
        jPanel1.add(loginbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 370, -1, -1));

        signupbtn.setBackground(new java.awt.Color(153, 0, 51));
        signupbtn.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        signupbtn.setForeground(new java.awt.Color(255, 255, 255));
        signupbtn.setText("Signup");
        signupbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupbtnActionPerformed(evt);
            }
        });
        jPanel1.add(signupbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 370, -1, -1));

        username.setBackground(java.awt.SystemColor.control);
        username.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        username.setToolTipText("Username");
        username.setSelectionColor(new java.awt.Color(153, 0, 0));
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        jPanel1.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 240, 170, 30));

        passtxt.setBackground(java.awt.SystemColor.control);
        passtxt.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        passtxt.setToolTipText("password");
        jPanel1.add(passtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 300, 170, 30));

        showbox.setBackground(java.awt.SystemColor.control);
        showbox.setFont(new java.awt.Font("Segoe UI Black", 1, 8)); // NOI18N
        showbox.setForeground(new java.awt.Color(153, 0, 51));
        showbox.setText("SHOWPASSWORD");
        showbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showboxActionPerformed(evt);
            }
        });
        jPanel1.add(showbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 340, 100, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/login.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 470));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void showboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showboxActionPerformed
        // TODO add your handling code here:
       if(showbox.isSelected()){
            passtxt.setEchoChar((char)0);
        }
        else{
            passtxt.setEchoChar('*');
        }
    }//GEN-LAST:event_showboxActionPerformed

    private void loginbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbtnActionPerformed
   
       String name = username.getText();
        String pass = new String(passtxt.getPassword());

        if (name.isEmpty() || pass.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Invalid email", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try (FileReader fr = new FileReader("txtlogin.txt"); Scanner reader = new Scanner(fr)) {
            reader.useDelimiter("[,\n]");

            boolean loginSuccess = false;

            while (reader.hasNext()) {
                String un = reader.next().trim();
                String pw = reader.next().trim();

                System.out.println("Checking username: " + un + " with password: " + pw); // Debug output

                if (name.equals(un) && pass.equals(pw)) {
                    loginSuccess = true;
                    break;
                }
            }

            if (loginSuccess) {
                homepage home = new homepage();
                setVisible(false);
                home.setVisible(true);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Invalid login details", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error reading login file: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
      
    }//GEN-LAST:event_loginbtnActionPerformed

    
    private void signupbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupbtnActionPerformed

       SignUp su = new SignUp();
       setVisible(false);
       su.setVisible(true);
       this.dispose();
       
     
    }//GEN-LAST:event_signupbtnActionPerformed

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void loginbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginbtnMouseClicked
        
    }//GEN-LAST:event_loginbtnMouseClicked

    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton loginbtn;
    private javax.swing.JPasswordField passtxt;
    private javax.swing.JCheckBox showbox;
    private javax.swing.JButton signupbtn;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
